#!/bin/bash
#
# check code quality

function pipe_if_not_empty {
  local title=$1
  shift

  head=$(dd bs=1 count=1 2>/dev/null; echo a)
  head=${head%a}

  if [ "x${head}" != x"" ]
  then
    { [ -n "$title" ] && echo "$title"; printf %s "${head}"; cat; } | "$@"
  fi
}

echo "Check Windows files with UNIX line terminators"
find . -name '*.ps1' -o -name '*.bat' -o -name '*.reg' -exec file {} \+| grep 'ASCII text' | grep -v 'CRLF' | pipe_if_not_empty "" cat | sed 's/^/ /;'

echo "Check unique name in checksum"
for f in $(awk '{print $2}' */checksum.txt | sort | uniq -c  | grep -v '^      1 ' | awk '{print $2}')
do
  if [ $(grep -h  $f */checksum.txt | sort -u | wc -l) -ne 1 ]
  then grep $f */checksum.txt
  fi
done | pipe_if_not_empty "" cat | sed 's/^/ /;'

echo "Check unique hash in checksum"
for f in $(awk '{print $1}' */checksum.txt | sort | uniq -c  | grep -v '^      1 ' | awk '{print $2}')
do
  if [ $(grep -h  $f */checksum.txt | sort -u | wc -l) -ne 1 ]
  then grep $f */checksum.txt
  fi
done | pipe_if_not_empty "" cat | sed 's/^/ /;'

echo "Check Makefile"
for m in */Makefile
do
  grep -q '^sinclude ../_common/conf.mk' "${m}" || echo "Makefile ${m} not include conf.mk"
  grep -q '^IT_TEAM:=' "${m}" || echo "Makefile ${m} not include IT_TEAM variable"
done | pipe_if_not_empty "" cat | sed 's/^/ /;'


echo "Check for unnecessary spaces at the end of lines for UNIX files"
ack -l --no-recurse --ignore-dir=tmp --ignore-dir=resources --ignore-file=ext:bat --ignore-file=ext:reg --ignore-file=ext:ini --ignore-file=ext:json --ignore-file=ext:ps1 --ignore-file=ext:psm1 --ignore-file=ext:psd1 --ignore-file=ext:log --ignore-file=ext:xml  '\s+$' ./ ./*/ | pipe_if_not_empty "" cat | sed 's/^/ /;'
echo "Check for unnecessary spaces at the end of lines for Windows files"
ack -l --ignore-dir=tmp --ignore-dir=resources '\s+\r$' ./ ./*/ | pipe_if_not_empty "" cat | sed 's/^/ /;'
