#!/bin/bash
#
# sum-versions: adds the sum of the numbers (major, minor, etc.) of a set of version numbers
#
# 2024/04/16 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

sum_versions() {
	result=''
	for index in 1 2 3 4
	do
		totalfield=0
		for version in $*
		do
			field=$(echo "${version}" | cut -f ${index} -d '.' | sed -e 's/^00*//;' | grep '[[:digit:]]' || echo '0')
			totalfield=$((${totalfield} + ${field}))
		done
		result="${result}.${totalfield}"
	done
	echo "${result}" | sed -e 's/^\.//;'
}

sum_versions $*
