#!/bin/bash
#
# 2024/12/05 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

url=$1

EXE=googlechromestandaloneenterprise64.msi
CHOCO=https://community.chocolatey.org/packages/GoogleChrome

function update_version () {
  local choco_url=$1

  while read version hash
  do
    if [ -s 'checksum.txt' ] && grep -q "^${hash}" 'checksum.txt'
    then
      return
    fi

    # 131.0.6778.86 9fcf15cb2390b84887b94e8e2f41d01eff325eccdac405e4f9a156dbc209689d
    # 9fcf15cb2390b84887b94e8e2f41d01eff325eccdac405e4f9a156dbc209689d  googlechromestandaloneenterprise64-131.0.6778.86.msi
    echo "${hash}  googlechromestandaloneenterprise64-${version}.msi" >> 'checksum.txt'
  done < <(curl -s -L "${choco_url}" | grep -E '^(\$version|\s\schecksum64)' | cut -f 2 -d ';' | cut -f 1 -d '&' | paste -sd ' ')
}

mkdir -p tmp
(cd tmp;
  # echo curl --time-cond "${EXE}" -o "${EXE}" -L "${url}" 1>&2;
  curl -s --time-cond "${EXE}" -o "${EXE}" -L "${url}")

if [ -s "tmp/${EXE}" ]
then
  HASHEXE=$(cd tmp; shasum -a 256 "${EXE}")

  # get new version from chocolatey
  grep -q "^${HASHEXE}" 'checksum.txt' || update_version "${CHOCO}"

  VERSION=$(grep "^${HASHEXE}" 'checksum.txt' | cut -f 2 -d '-' | sed 's/\.msi//;')
  if echo ${VERSION} | grep -q '[[:digit:]][[:digit:]\.]*'
  then
    echo ${VERSION}
  else
    echo ''
  fi
else
  echo ''
fi
