#!/bin/bash

mkdir -p tmp
cd tmp || exit

URL=$(curl -s -L --connect-timeout 10 'https://nmap.org/download.html' | sed -e 's/"/\n/g;' | grep -E '^https://.*/nmap-.*-setup.exe')
NMAP_EXE=$(basename "${URL}")

if [ ! -e "${NMAP_EXE}" ]
then
  rm -f nmap-7.93-setup.exe npcap-*.exe

  curl -s -L "${URL}" -o "${NMAP_EXE}"
fi

if [ "$(ls -1 npcap-*.exe 2> /dev/null | wc -l)" -lt 1 ]
then
  NPCAP=$(7z l "${NMAP_EXE}" | grep -Ei 'npcap-.*exe' | awk '{print $5}')
fi

VERSION=$( (basename "${NPCAP}"; basename npcap-*.exe) | sed -e 's/\.exe$//;' | cut -f 2 -d '-' | grep '^[[:digit:]]')
if [ ! -e "npcap-${VERSION}.exe" ]
then
  7z -y e "${NMAP_EXE}" "${NPCAP}" > /dev/null
fi

if [ -e "npcap-${VERSION}.exe" ]
then
  echo "${VERSION}"
else
  echo 'error'
fi
